# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 01:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('emergency_contact_name', models.CharField(max_length=25)),
                ('emergency_contact_number', models.CharField(max_length=13)),
                ('dog_name', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('breed', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=3)),
                ('dob', models.DateField()),
                ('friendly_with_kids', models.CharField(max_length=3)),
                ('friendly_with_dogs', models.CharField(max_length=3)),
                ('spray_neutered', models.CharField(max_length=3)),
                ('medical_conditions', models.CharField(max_length=3)),
                ('specify_condition', models.TextField(max_length=200)),
                ('requires_medication', models.CharField(max_length=3)),
                ('which_medication', models.TextField(max_length=200)),
                ('house_trained', models.CharField(max_length=3)),
                ('separation_anxiety', models.CharField(max_length=3)),
                ('feel_at_home', models.TextField(max_length=200)),
                ('legible_tags', models.CharField(max_length=3)),
                ('good_on_leash', models.TextField(max_length=100)),
                ('food_brand', models.CharField(max_length=25)),
                ('directions', models.TextField(max_length=100)),
                ('treats', models.CharField(max_length=3)),
                ('food_allergy', models.TextField(max_length=200)),
                ('vet_name', models.CharField(max_length=25)),
                ('ver_phone_number', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
