# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=6)),
                ('breed', models.CharField(max_length=30)),
                ('size', models.IntegerField(max_length=3)),
                ('birthday', models.DateField()),
                ('kids', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
                ('friendly_dogs', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
                ('vaccination', models.BooleanField(choices=[('rabies', 'Rabies'), ('bordetella', 'Bordetella'), ('DHLP', 'dhlp')], max_length=10)),
                ('neutered', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
                ('medical_condition', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
                ('medical_condition_description', models.TextField()),
                ('medication', models.BooleanField(choices=[('Yes', 'yes'), ('No', 'no')])),
                ('medication_type', models.TextField()),
                ('house_trained', models.BooleanField(choices=[('Yes', 'yes'), ('No', 'no')])),
                ('sep_anxiety', models.BooleanField(choices=[('Yes', 'yes'), ('No', 'no')])),
                ('feel_at_home', models.TextField()),
                ('tags', models.BooleanField(choices=[('Yes', 'yes'), ('No', 'no')])),
                ('leash', models.TextField()),
                ('brand', models.CharField(max_length=30)),
                ('directions', models.TextField()),
                ('feed_time', models.TimeField()),
                ('treats', models.BooleanField(choices=[('Yes', 'yes'), ('No', 'no')])),
                ('allergy', models.BooleanField(choices=[('Dairy', 'Dairy'), ('Chicken', 'chicken'), ('Peanut Butter', 'peanut butter'), ('Peas', 'peas'), ('Pumpkin', 'pumpkin'), ('Rice', 'rice'), ('Other', 'other'), ('none', 'None')])),
                ('allergy_other', models.TextField()),
                ('parent_name', models.CharField(max_length=25)),
                ('telephone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=35)),
                ('address', models.CharField(max_length=250)),
                ('zip', models.CharField(max_length=5)),
                ('emergency_contact_name', models.CharField(max_length=25)),
                ('emergency_contact_number', models.CharField(max_length=12)),
                ('vet_name', models.CharField(max_length=25)),
                ('ver_number', models.CharField(max_length=12)),
                ('sig', models.CharField(max_length=30)),
                ('date_signed', models.DateField()),
            ],
        ),
    ]
