# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupinfo',
            old_name='allergy_other',
            new_name='any_allergies',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='tags',
            new_name='clearly_identifiable_dog_tags',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='directions',
            new_name='dog_good_on_leash',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='brand',
            new_name='dogs_name',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='dog_name',
            new_name='food_brand',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='leash',
            new_name='food_directions',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='friendly_dogs',
            new_name='friendly_with_kids',
        ),
        migrations.RenameField(
            model_name='pupinfo',
            old_name='kids',
            new_name='friendly_with_other_dogs',
        ),
        migrations.RemoveField(
            model_name='pupinfo',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='pupinfo',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pupinfo',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='pupinfo',
            name='DHLP_vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pupinfo',
            name='bordetella_vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pupinfo',
            name='rabies_vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pupinfo',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
