# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20160719_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupinfo',
            old_name='feed_time',
            new_name='breakfast_feed_time',
        ),
        migrations.AddField(
            model_name='pupinfo',
            name='dinner_feed_time',
            field=models.TimeField(default=datetime.datetime(2016, 7, 20, 3, 24, 12, 527847, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pupinfo',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pupinfo',
            name='clearly_identifiable_dog_tags',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pupinfo',
            name='house_trained',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pupinfo',
            name='medication',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pupinfo',
            name='sep_anxiety',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pupinfo',
            name='treats',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3),
        ),
    ]
