# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20160719_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conctact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=25)),
                ('telephone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=35)),
                ('address', models.CharField(max_length=250)),
                ('zip', models.CharField(max_length=5)),
                ('emergency_contact_name', models.CharField(max_length=25)),
                ('emergency_contact_number', models.CharField(max_length=12)),
                ('vet_name', models.CharField(max_length=25)),
                ('ver_number', models.CharField(max_length=12)),
                ('sig', models.CharField(max_length=30)),
                ('date_signed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogs_name', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogFeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_brand', models.CharField(max_length=30)),
                ('food_directions', models.TextField()),
                ('breakfast_feed_time', models.TimeField()),
                ('dinner_feed_time', models.TimeField()),
                ('treats', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('any_allergies', models.TextField()),
                ('dog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('breed', models.CharField(max_length=20)),
                ('weight_pounds', models.IntegerField()),
                ('birthday', models.DateField()),
                ('friendly_with_kids', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('friendly_with_other_dogs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('house_trained', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('feel_at_home', models.TextField()),
                ('clearly_identifiable_dog_tags', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('dog_good_on_leash', models.TextField()),
                ('dog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='DogMedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rabies_vaccination', models.BooleanField(default=False)),
                ('bordetella_vaccination', models.BooleanField(default=False)),
                ('DHLP_vaccination', models.BooleanField(default=False)),
                ('neutered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('medical_condition', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('medical_condition_description', models.TextField()),
                ('medication', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('medication_type', models.TextField()),
                ('separation_anxiety', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('dog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Dog')),
            ],
        ),
        migrations.DeleteModel(
            name='PupInfo',
        ),
        migrations.AddField(
            model_name='conctact',
            name='dog_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Dog'),
        ),
    ]
