# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20160720_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conctact',
            new_name='Contact',
        ),
    ]
