# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20160720_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogs_name',
            field=models.CharField(default=datetime.datetime(2016, 7, 22, 22, 1, 8, 656907, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
